# Standards: 0.1
---
- name: Kill sublime-text
  command: killall Sublime\ Text
  register: sublime_text_kill
  failed_when: sublime_text_kill.rc != 0 and "No matching processes belonging to you were found" not in google_chrome_kill.stderr
  become: "{{ (sublime_text_user != ansible_user_id) | bool }}"
  become_user: "{{ sublime_text_user }}"

- name: Start sublime-text
  when: sublime_text_started
  command: open -j /Applications/Sublime\ Text.app
  become: "{{ (sublime_text_user != ansible_user_id) | bool }}"
  become_user: "{{ sublime_text_user }}"

...
